FROM pytorch/torchserve:0.11.0-gpu as builder

USER root

RUN apt-get update && apt-get install -y ffmpeg

WORKDIR /app

COPY ./chat-tts-ui ./

RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

RUN pip uninstall -y torch torchvision torchaudio \
    && pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu121